services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on: 
      - db
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contatos
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
    ports:
      - "3306:3306"